### ISSUE TITLE
Support pydantic2

### ISSUE THREAD

**Issue by jozo** [StationA/gke-logging#5]
Hi, thank for your package. Can you add support for pydantic2?

**Comment by jerluc** [comment]
> Can you add support for pydantic2?

@jozo I think this should be doable. There's only a couple of wrinkles to iron out, where Pydantic's API has slightly changed (e.g. `BaseModel.json()` in v1 is now called `BaseModel.model_dump_json()` in v2 according to [their migration docs](https://docs.pydantic.dev/latest/migration/)).

PRs are welcome! Otherwise this one might take us a while to get to since we largely remain on Pydantic v1.

**Comment by jerluc** [comment]
Support for pydantic v2+ has been in added in [v0.1.0](https://github.com/StationA/gke-logging/releases/tag/v0.1.0)
